[package]
name = "sllv-core"
version = "0.0.23"
edition = "2021"

[dependencies]
anyhow               = { workspace = true }
thiserror            = { workspace = true }
serde                = { workspace = true }
serde_json           = { workspace = true }
sha2                 = { workspace = true }
hex                  = { workspace = true }
crc32fast            = { workspace = true }
image                = { workspace = true }
reed-solomon-erasure = { workspace = true }
tar                  = { workspace = true }
nalgebra             = { workspace = true }
walkdir              = { workspace = true }
